# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  demands: 
    - DotNetFramework
    - msbuild
    - visualstudio
    - vstest
    - windows10

steps:
- checkout: self

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'WpfApp.sln'
- task: NodeTool@0
  inputs:
    versionSpec: '6.x'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\AppiumTests.dll
    searchFolder: '$(System.DefaultWorkingDirectory)'